import { Case } from "./types";

export const cases: Case[] = [
  {
    id: "zeit-audio-briefing", title: "ZEIT erweitert das tägliche News-Briefing um ein Audio-Erlebnis", source: "DIE ZEIT", sourceType: "Publisher", url: "https://www.zeit.de", medium: "Audio", sector: "Publisher", market: "DACH", platform: "Web & App", format: "News-Briefing", tags: ["Routine", "Personalisierung", "Podcast"], publishedAt: "2026-07-29", status: "Freigegeben", isNew: true,
    excerpt: "Ein kompaktes Hörformat verbindet aktuelle Nachrichten mit persönlichen Themeninteressen.", context: "Morgendliche Nachrichtenroutine auf mobilen Endgeräten.", action: "Text-Briefing als hörbaren, modularen Feed ausspielen.", summary: "Audio wird als tägliche Nutzungsroutine eingesetzt und macht das Briefing auch unterwegs relevant.", metrics: [{ label: "Hördauer", value: "nicht veröffentlicht", source: "Quellenbeitrag" }, { label: "Abos", value: "nicht veröffentlicht", source: "Quellenbeitrag" }]
  },
  {
    id: "vg-short-video", title: "VG setzt auf vertikale Kurzvideos für jüngere Zielgruppen", source: "INMA", sourceType: "Netzwerk", url: "https://www.inma.org/blogs/Video-Innovations/", medium: "Video", sector: "Publisher", market: "International", platform: "Web & App", format: "Short-form Video", tags: ["Social Video", "Gen Z", "Vertical"], publishedAt: "2026-07-27", status: "Freigegeben", isNew: true,
    excerpt: "Der Publisher optimiert Nachrichtenformate für mobile Feeds und Beteiligung.", context: "Nachrichtenmarke will eine jüngere mobile Zielgruppe erreichen.", action: "Story-first-Produktion in vertikalen Episoden mit klarer Interaktion.", summary: "Native Kurzvideo-Formate funktionieren besser, wenn Redaktion und Distribution gemeinsam geplant werden.", metrics: [{ label: "Views", value: "3,1 Mio.", source: "INMA Case Study" }, { label: "Engagement", value: "nicht veröffentlicht", source: "INMA Case Study" }]
  },
  {
    id: "duolingo-video", title: "Duolingo baut eine wiedererkennbare Kurzvideo-Identität auf", source: "Digiday", sourceType: "Netzwerk", url: "https://digiday.com", medium: "Video", sector: "Andere Branchen", market: "International", platform: "Web & App", format: "Creator Video", tags: ["Brand Voice", "TikTok", "Community"], publishedAt: "2026-07-24", status: "Freigegeben", excerpt: "Eine klare, wiederholbare Figurenwelt verwandelt Produktkommunikation in Serieninhalte.", context: "Marke kämpft um Aufmerksamkeit in algorithmischen Feeds.", action: "Wiedererkennbare Host-Persona mit wiederkehrenden Videoformaten etablieren.", summary: "Eine konsistente kreative Handschrift ist für organische Videoreichweite wertvoller als Hochglanzproduktion.", metrics: [{ label: "Reichweite", value: "nicht veröffentlicht", source: "Digiday" }]
  },
  {
    id: "nzz-explainer", title: "Erklärvideo-Format bündelt komplexe Themen für App und Website", source: "WAN-IFRA", sourceType: "Netzwerk", url: "https://wan-ifra.org", medium: "Video", sector: "Publisher", market: "DACH", platform: "Web & App", format: "Explainer", tags: ["Evergreen", "Produkt", "Subscription"], publishedAt: "2026-07-21", status: "Freigegeben", excerpt: "Ein wiederverwendbares Erklärformat ergänzt die laufende Berichterstattung.", context: "Komplexe Themen sollen verständlich und langfristig auffindbar sein.", action: "Einheitliche Erklärvideo-Vorlage an Themencluster statt Einzelartikel koppeln.", summary: "Video entfaltet zusätzlichen Wert, wenn es als langlebiges Produktmodul statt als Begleitmaterial entsteht.", metrics: [{ label: "Completion Rate", value: "68 %", source: "WAN-IFRA Case Study" }, { label: "Produktionsaufwand", value: "nicht veröffentlicht", source: "WAN-IFRA Case Study" }]
  },
  {
    id: "headspace-audio", title: "Headspace personalisiert Audio-Momente entlang des Tagesverlaufs", source: "The Audiencers", sourceType: "Netzwerk", url: "https://theaudiencers.com", medium: "Audio", sector: "Andere Branchen", market: "International", platform: "App", format: "Personalisierte Audio-Serie", tags: ["Retention", "Onboarding", "Routine"], publishedAt: "2026-07-19", status: "Freigegeben", excerpt: "Kurze Audioformate werden passend zu Tageszeit und Nutzungsverhalten angeboten.", context: "Eine App will langfristige Gewohnheiten statt einmaliger Nutzung schaffen.", action: "Inhaltliche Audio-Impulse über eine nutzerfreundliche Tagesroutine orchestrieren.", summary: "Die Kontextualisierung nach Moment und Bedarf kann die Rückkehr häufiger auslösen als ein großer Katalog.", metrics: [{ label: "Retention", value: "nicht veröffentlicht", source: "The Audiencers" }]
  },
  {
    id: "podcast-review", title: "Lokaler Podcast mit Live-Komponente und Abo-Mehrwert", source: "INMA", sourceType: "Netzwerk", url: "https://www.inma.org", medium: "Audio", sector: "Publisher", market: "International", platform: "Web & App", format: "Podcast / Live", tags: ["Live", "Monetarisierung", "Lokal"], publishedAt: "2026-07-18", status: "In Prüfung", excerpt: "Ein lokales Nachrichtenformat kombiniert Podcast-Ausgabe und zeitnahe Live-Updates.", context: "Publisher sucht zusätzliche Bindung für eine loyale lokale Zielgruppe.", action: "Podcast als Teil eines kontinuierlichen lokalen Informationsprodukts denken.", summary: "Noch zu prüfen: Die Kombination aus regelmäßiger Episode und Live-Momenten kann die Bindung erhöhen.", metrics: []
  }
];

export const sourceNames = ["Alle Quellen", "INMA", "The Audiencers", "WAN-IFRA", "Nieman Lab", "Digiday", "DIE ZEIT"];
