"use client";

import { type FormEvent, useState } from "react";
import type { PublisherScanTargetOverview } from "@/lib/discovery-types";
import type { SourceOverview } from "@/lib/dashboard-data";

export default function ScanTargetManager({ targets, sources }: { targets: PublisherScanTargetOverview[]; sources: SourceOverview[] }) {
  const [open, setOpen] = useState(false); const [message, setMessage] = useState("");
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch("/api/publisher-scan-targets", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ publisherSourceId: form.get("publisherSourceId"), url: form.get("url"), targetType: form.get("targetType") }) }); if (!response.ok) { const body = await response.json(); setMessage(body.error ?? "Scan-Ziel konnte nicht gespeichert werden."); return; } window.location.reload(); }
  async function toggle(target: PublisherScanTargetOverview) { await fetch(`/api/publisher-scan-targets/${target.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ active: !target.active }) }); window.location.reload(); }
  return <section className="scan-targets"><div><p className="eyebrow">SCAN-ZIELE</p><h2>Öffentliche Publisher-Flächen</h2><p>Startseiten werden automatisch angelegt. Ergänze gezielt Audio-/Video-Hubs, Hilfeseiten oder öffentliche App-Store-Seiten.</p></div><button className="outline" onClick={() => setOpen(!open)}>{open ? "Abbrechen" : "+ Scan-Ziel"}</button>{open && <form onSubmit={save}><label>Publisher<select name="publisherSourceId" required defaultValue=""><option value="" disabled>Publisher auswählen</option>{sources.map((source) => <option value={source.id} key={source.id}>{source.name}</option>)}</select></label><label>Zieltyp<select name="targetType" defaultValue="help"><option value="audio_hub">Audio-Hub</option><option value="video_hub">Video-Hub</option><option value="help">Hilfe-/Produktseite</option><option value="app_store">Öffentliche App-Store-Seite</option><option value="website">Website</option></select></label><label>URL<input name="url" type="url" required placeholder="https://…" /></label><button className="primary">Speichern</button></form>}{message && <p className="form-message">{message}</p>}<div className="scan-target-list">{targets.map((target) => <div key={target.id}><strong>{target.publisher}</strong><span>{target.targetType}</span><a href={target.url} target="_blank" rel="noreferrer">{target.url}</a><button className="outline" onClick={() => toggle(target)}>{target.active ? "Pausieren" : "Aktivieren"}</button></div>)}</div></section>;
}
