"use client";

import { type FormEvent, useState } from "react";
import type { TrendEvidence, TrendSignal } from "@/lib/types";
import type { SourceOverview } from "@/lib/dashboard-data";

export default function TrendToPublisher({ trend, evidence, sources, onClose }: { trend: TrendSignal; evidence: TrendEvidence; sources: SourceOverview[]; onClose: () => void }) {
  const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/publisher-features", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ sourceId: form.get("sourceId"), observedFeature: form.get("observedFeature"), productFeatureId: "", originTrendId: trend.id, platforms: String(form.get("platforms") ?? "").split(",").map((item) => item.trim()).filter(Boolean), status: "Aktuell dokumentiert", evidenceQuality: "Branchenquelle", evidenceUrl: evidence.url, evidenceLabel: `${evidence.source}: ${evidence.title}`, notes: `Aus Trend-Radar übernommen: ${trend.title}` }) }); const body = await response.json(); setSaving(false); if (!response.ok) { setError(body.error ?? "Übernahme nicht möglich."); return; } window.location.reload(); }
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="trend-transfer" onSubmit={submit} onMouseDown={(event) => event.stopPropagation()}><button type="button" className="close" onClick={onClose}>×</button><p className="eyebrow">IN PUBLISHER-MONITOR ÜBERNEHMEN</p><h2>{trend.title}</h2><p>Der INMA-/Branchenbeleg wird als „Branchenquelle“ gespeichert und mit diesem Trend verknüpft.</p><label>Publisher<select name="sourceId" required defaultValue=""><option value="" disabled>Publisher auswählen</option>{sources.map((source) => <option value={source.id} key={source.id}>{source.name}</option>)}</select></label><label>Beobachtetes Feature<input name="observedFeature" defaultValue={evidence.title} required /></label><label>Plattformen<input name="platforms" placeholder="Web, App, E-Paper" /></label><label>Beleg<input value={`${evidence.source}: ${evidence.title}`} readOnly /></label>{error && <p className="form-message">{error}</p>}<footer><button type="button" className="outline" onClick={onClose}>Abbrechen</button><button className="primary" disabled={saving}>{saving ? "Übernimmt…" : "In Monitor übernehmen"}</button></footer></form></div>;
}
