"use client";

import { type FormEvent, useState } from "react";
import type { ProductFeature, TrendSignal } from "@/lib/types";

const statusClass: Record<string, string> = { "Abgedeckt": "covered", "Lücke": "gap", "Beobachten": "watch", "Pionier": "pioneer" };

export default function TrendRadar({ trends, features }: { trends: TrendSignal[]; features: ProductFeature[] }) {
  const [showForm, setShowForm] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  async function createTrend(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/trends", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: form.get("title"), summary: form.get("summary"), area: form.get("area"), maturity: form.get("maturity") }) }); const body = await response.json(); setSaving(false); if (!response.ok) { setMessage(body.error ?? "Trend konnte nicht angelegt werden."); return; } window.location.reload(); }
  return <div className="trend-page"><p className="eyebrow">TREND-RADAR</p><h1>Was verändert sich <em>jetzt?</em></h1><p className="trend-intro">Verdichtete Branchenentwicklungen mit konkreten Belegen und direktem Abgleich mit unserem Angebot.</p><div className="trend-legend"><span><i className="covered" /> Abgedeckt</span><span><i className="gap" /> Lücke</span><span><i className="watch" /> Beobachten</span><span><i className="pioneer" /> Pionier</span><button className="outline" onClick={() => setShowForm((current) => !current)}>{showForm ? "Abbrechen" : "+ Trend erfassen"}</button></div>{showForm && <form className="trend-form" onSubmit={createTrend}><label>Titel<input name="title" required placeholder="z. B. KI-generierte News-Briefings" /></label><label>Einordnung<textarea name="summary" required placeholder="Was verändert sich, welche Beispiele belegen das und warum ist es relevant?" /></label><label>Bereich<select name="area" defaultValue="Audio"><option>Audio</option><option>Video</option><option>Audio & Video</option></select></label><label>Reifegrad<select name="maturity" defaultValue="Frühes Signal"><option>Frühes Signal</option><option>Im Aufschwung</option><option>Branchenstandard</option></select></label><button className="primary" disabled={saving}>{saving ? "Speichert…" : "Als Entwurf anlegen"}</button></form>}{message && <p className="form-message">{message}</p>}<section className="trend-list">{trends.length ? trends.map((trend) => <article className="trend-card" key={trend.id}><header><div><span className="trend-area">{trend.area}</span><span className="trend-maturity">{trend.maturity}</span></div><small>{trend.status} · beobachtet seit {new Intl.DateTimeFormat("de-DE", { dateStyle: "medium" }).format(new Date(trend.observedAt))}</small></header><h2>{trend.title}</h2><p>{trend.summary}</p><div className="trend-compare"><strong>Abgleich mit unserem Angebot</strong>{trend.assessments.length ? trend.assessments.map((assessment) => { const feature = features.find((item) => item.id === assessment.featureId); return <div key={`${assessment.featureId}-${assessment.status}`}><span className={`trend-state ${statusClass[assessment.status]}`}>{assessment.status}</span><b>{feature?.title ?? "Nicht zugeordnet"}</b><small>{assessment.rationale}</small></div>; }) : <span className="muted">Noch kein Feature-Abgleich hinterlegt.</span>}</div>{trend.evidence.length ? <footer><strong>Belege</strong>{trend.evidence.map((evidence) => <a key={evidence.id} href={evidence.url} target="_blank">{evidence.source}: {evidence.title} ↗</a>)}</footer> : <footer><span className="muted">Für die Veröffentlichung fehlen noch Quellenbelege.</span></footer>}</article>) : <div className="empty-state"><strong>Noch keine Trends veröffentlicht.</strong><span>Erfassen Sie einen ersten Entwurf aus einer beobachteten Entwicklung; Belege und Feature-Abgleich können danach ergänzt werden.</span></div>}</section></div>;
}
