"use client";

import { type FormEvent, useState } from "react";
import type { ProductFeature, TrendSignal } from "@/lib/types";
import TrendEditor from "./trend-editor";

export default function TrendRadar({ trends, features }: { trends: TrendSignal[]; features: ProductFeature[] }) {
  const [showForm, setShowForm] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [editing, setEditing] = useState<TrendSignal | null>(null);
  async function createTrend(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/trends", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: form.get("title"), summary: form.get("summary"), area: form.get("area"), maturity: form.get("maturity") }) }); const body = await response.json(); setSaving(false); if (!response.ok) { setMessage(body.error ?? "Trend konnte nicht angelegt werden."); return; } window.location.reload(); }
  return <div className="trend-page"><p className="eyebrow">TREND-RADAR</p><h1>Was verändert sich <em>jetzt?</em></h1><p className="trend-intro">Automatisch gebündelte Themen – mit direkten Fundstellen und ihrer Relevanz für unser Angebot.</p><div className="trend-legend"><span>Neue Signale erscheinen direkt nach dem Quellenimport.</span><button className="outline" onClick={() => setShowForm((current) => !current)}>{showForm ? "Abbrechen" : "+ Thema ergänzen"}</button></div>{showForm && <form className="trend-form" onSubmit={createTrend}><label>Titel<input name="title" required placeholder="z. B. KI-generierte News-Briefings" /></label><label>Einordnung<textarea name="summary" required placeholder="Was ist die Entwicklung und warum ist sie relevant?" /></label><label>Bereich<select name="area" defaultValue="Audio"><option>Audio</option><option>Video</option><option>Audio & Video</option></select></label><label>Reifegrad<select name="maturity" defaultValue="Frühes Signal"><option>Frühes Signal</option><option>Im Aufschwung</option><option>Branchenstandard</option></select></label><button className="primary" disabled={saving}>{saving ? "Speichert…" : "Thema hinzufügen"}</button></form>}{message && <p className="form-message">{message}</p>}<section className="trend-list">{trends.length ? trends.map((trend) => <article className="trend-card" key={trend.id}><header><div><span className="trend-area">{trend.area}</span><span className="trend-maturity">{trend.maturity}</span>{trend.origin === "Automatisch erkannt" && <span className="trend-origin">Automatisch erkannt</span>}</div><div className="trend-card-actions"><small>beobachtet seit {new Intl.DateTimeFormat("de-DE", { dateStyle: "medium" }).format(new Date(trend.observedAt))}</small><button className="outline" onClick={() => setEditing(trend)}>Bearbeiten</button></div></header><h2>{trend.title}</h2><p>{trend.summary}</p><div className="trend-compare"><strong>Relevant für unser Angebot</strong>{trend.assessments.length ? trend.assessments.map((assessment) => { const feature = features.find((item) => item.id === assessment.featureId); return <div key={assessment.featureId}><b>{feature?.title ?? "Nicht zugeordnet"}</b><small>{assessment.rationale}</small></div>; }) : <span className="muted">Noch keinem internen Feature zugeordnet.</span>}</div><footer>{trend.evidence.length ? <><strong>Belege: Wo das Feature erwähnt oder genutzt wird</strong>{trend.evidence.map((evidence) => <a key={evidence.id} href={evidence.url} target="_blank">{evidence.source}: {evidence.title} ↗</a>)}</> : <span className="muted">Noch keine Belege hinterlegt.</span>}</footer></article>) : <div className="empty-state"><strong>Noch keine Trend-Signale.</strong><span>Nach dem nächsten Quellenimport erscheinen automatisch erkannte Themen hier direkt mit ihren Belegen.</span></div>}</section>{editing && <TrendEditor trend={editing} features={features} onClose={() => setEditing(null)} onSaved={() => window.location.reload()} />}</div>;
}
